version: "3"

services:
  app:
    build: .
    volumes:
      - .:/go/src/

  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/